# Generated by Django 4.0.4 on 2023-03-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='asked_questions',
            field=models.ManyToManyField(related_name='asked_questions', to='questions.question'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questions.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='results',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
