# Generated by Django 4.1.7 on 2023-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_authuser_current_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='avatar'),
        ),
    ]
