# Generated by Django 4.1.7 on 2023-03-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_rating_delete_remark"),
        ("authapp", "0005_remark_questionratedbyuser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionratedbyuser", unique_together={("question", "user")},
        ),
    ]
