# Generated by Django 4.1.7 on 2023-03-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_rating_delete_remark"),
        ("authapp", "0006_alter_questionratedbyuser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="remark", unique_together={("question", "author")},
        ),
    ]
