# games: players and level
QUEUE_LEVEL_RANGE = 5
GAME_MAX_PLAYERS = 2

# games: questions and answers
GAME_QUESTIONS_COUNT = 3
GAME_ANSWERS_COUNT = 4
GAME_SUBTYPE_ANSWERS_COUNT = 2

# games: time
GAME_TIME_BEFORE_START = 5
GAME_TIME_TO_ANSWER = 10
GAME_TIME_SHOW_ANSWER = 3

# games: points
GAME_POINTS_FOR_CORRECT = 1
GAME_POINTS_FOR_FASTEST = 1

# games: xp
XP_PER_LEVEL = 1000
XP_PER_GAME = 1000
XP_FIRST_PLACE_BONUS = 200
XP_OUT_OF_LEVEL_BONUS_RATIO = 0.2

# for models
NULLABLE = {"blank": True, "null": True}
