# Generated by Django 4.1.7 on 2023-03-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
    ]
