# Generated by Django 4.1.7 on 2023-04-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_category_options_alter_subtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
